dataset: "ccdv/govreport-summarization"
model:
  name: "TheBloke/Mistral-7B-Instruct-v0.1-GGUF"
  file: "mistral-7b-instruct-v0.1.Q4_K_M.gguf"
  type: "mistral"
  config:
    context_length: 4096
    max_new_tokens: 1024
    batch_size: 512
    threads: 6